### PR TITLE
Migration to new IntellijIDEA version

### PR DESCRIPTION
**Pull request by isnullxbh**

### CODE REVIEW

**Comment by Saigut** [comment]
Hi, I have not find the changes about JDK 10. Is it necessary update to JDK 10? 
And I see that the changes you made are not very necessary?

**Comment by isnullxbh** [comment]
Hi Saigut!
> And I see that the changes you made are not very necessary?

I have installed the new intellij-community and tried to compile your plugin. Compiling was failure due to next reasons:
- in new intellij-community version @Storage doesn't have property ID
- signature of execute method was changed, so, your version of function definition is wrong
- last commit in request - this is auto updated information :)

**Comment by isnullxbh** [comment]
Excuse me, Saigut! I gave the wrong description for made changes. My objective was a fixing a compatibility with new IntellijIDEA version.

**Comment by Saigut** [comment]
Well, I will update intellij-community and test about this after work.

**Comment by isnullxbh** [comment]
Thanks Saigut!

**Pull request closed without merging**
